# Generated by Django 4.1.5 on 2023-05-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="task",
            fields=[
                ("serial", models.AutoField(primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=50)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
