# Generated by Django 4.1.5 on 2023-05-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="task", new_name="Tasks",),
    ]
